python ./source/inference.py \
    --base_dir . \
    --test_csv ./push_code/out_csv/test.csv \
    --p8_feature_dir ./ViT_p8_448_0.5 \
    --p16_feature_dir ./ViT_p16_448_0.5 \
    --abmil_p8_weight ./ckpt/weighted/abmil8_.pth \
    --abmil_p16_weight ./ckpt/weighted/abmil16.pth \
    --dsmil_p8_weight ./ckpt/dsmil8.pth \
    --dsmil_p16_weight ./ckpt/dsmil16.pth \
    --num_worker 64 \
    --save_result_df ./result_df/result.csv \
    --infer_p8 \
    --infer_p16 \
    --infer_abmil \
    --infer_dsmil \
    --abmil_p8 0.25 \
    --abmil_p16 0.25 \
    --dsmil_p8 0.25 \
    --dsmil_p16 0.25
